# permissions for end users to view example-platforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: example-platform-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atk
    app.kubernetes.io/part-of: atk
    app.kubernetes.io/managed-by: kustomize
  name: example-platform-viewer-role
rules:
- apiGroups:
  - operators.my.domain
  resources:
  - example-platforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.my.domain
  resources:
  - example-platforms/status
  verbs:
  - get
