/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("atk.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("ch.qos.logback:logback-classic:1.4.8")
    implementation("com.typesafe:config:1.4.2")
    implementation("io.smallrye.reactive:mutiny:2.3.1")
    implementation("org.evrete:evrete-core:3.0.03")
    implementation("org.evrete:evrete-dsl-java:3.0.03")
    implementation("org.optaplanner:optaplanner-bom:9.41.0.Final")
    implementation("org.optaplanner:optaplanner-core:9.41.0.Final")
}

application {
    // Define the main class for the application.
    mainClass.set("atk.app.App")
}
